active_label: 1
channels:
- active: false
  name: DAPI
- active: false
  name: TRITC
- active: false
  name: CY5
- active: false
  name: FITC
data_key: features
image_cache_size: 100
image_key: images
labels:
- active: false
  name: class 0
- active: true
  name: CTC
- active: true
  name: CAF
- active: true
  name: CEC
- active: true
  name: Mega
- active: true
  name: Junk
- active: false
  name: PIC-WBC
mask_key: masks
output_dir: /home/dean/Desktop/annotateEZ/New Folder
tile_size: 75
x_size: 15
y_size: 7
