name: annotateez
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyqt>=5.15.0
  - pandas>=1.3.0
  - numpy>=1.21.0
  - h5py>=3.1.0
  - pyyaml>=5.4.0
  - pytables>=3.7.0
  - pip
  - pip:
    # Add any pip-only dependencies here if needed
